version: 0.2
run-as: root
phases:

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region us-east-1) 
      - docker login --username (username) --password (password) 
      - REPOSITORY_URI=484912964803.dkr.ecr.us-east-1.amazonaws.com/work
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t work:latest -f "${DockerFilePath}" .
      - docker tag work:latest 484912964803.dkr.ecr.us-east-1.amazonaws.com/work:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 484912964803.dkr.ecr.us-east-1.amazonaws.com/work:latest
      - echo Writing image definitions file...
      - printf '[{"name":"%s"imageUri":"%s"}]' 484912964803.dkr.ecr.us-east-1.amazonaws.com/work:latest > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
